apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-foodme
  labels:
    app: app-foodme
    version: "1.0.0"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-foodme
  template:
    metadata:
      labels:
        app: app-foodme
        version: "1.0.0"
    spec:
      containers:
      - name: app-foodme
        image: nandocloud/app-delivery:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5