apiVersion: v1
kind: Service
metadata:
  name: app-foodme
  labels:
    app: app-foodme
spec:
  type: LoadBalancer
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: app-foodme