apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-foodme
spec:
  template:
    spec:
      containers:
      - name: app-foodme
        env:
        - name: NODE_ENV
          value: "qa"
        - name: ENVIRONMENT
          value: "qa"
        - name: LOG_LEVEL
          value: "info"
        - name: PORT
          value: "3000"