apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-foodme
spec:
  template:
    spec:
      containers:
      - name: app-foodme
        env:
        - name: NODE_ENV
          value: "production"
        - name: ENVIRONMENT
          value: "production"
        - name: LOG_LEVEL
          value: "warn"
        - name: PORT
          value: "3000"
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"