# This workflow has been replaced by environment-promotion-v2.yml
# This file is kept for reference but is no longer active

# To remove this file completely, delete it manually from GitHub web interface